# site settings
title: Kartik Luke Singh
subtitle: Building great products one step at a time
email: me@kartikluke.com
description: I'm Kartik, a web developer currently living in Bangalore, IN<br />When I'm not composing code or brainstorming how to tackle that next issue, you'll find me reading, or out playing basketball.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 622, Jal Vayu Towers, Temple Road
city: Bangalore
state: KN
zip_code: 560038
country: India
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/kartikluke
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/kartikluke

# build settings
markdown: kramdown

sass:
  style: compressed
